server:
  port: 7101
spring:
  application:
    name: shop-service-user
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  datasource:
    url: jdbc:mysql://localhost:3306/saas-shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
mybatis:
  mapper-locations:
    - classpath*:com/sunny/user/mapper/*.xml
    - classpath*:com/sunny/user/mapper/extend/*.xml
  configuration:
    map-underscore-to-camel-case: true
feign:
  hystrix:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
      fetch-registry: true
      register-with-eureka: true
#admin client的配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    path: shop-server-user.log #添加开启admin的日志监控
  level:
    root: info
jwt:
  tokenHeader:  Authorization
  tokenHead:  Bearer
  secret: tec_feng
  expiration: 604800
