server:
  port: 7002
spring:
  application:
    name: shop-monitor
  security:
      user:
        name: admin
        password: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/